# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tais_core import attentiondb_pb2 as attentiondb__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in attentiondb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AttentionDBStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Attend = channel.unary_unary(
                '/attentiondb.AttentionDB/Attend',
                request_serializer=attentiondb__pb2.AttendRequest.SerializeToString,
                response_deserializer=attentiondb__pb2.AttendResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/attentiondb.AttentionDB/Insert',
                request_serializer=attentiondb__pb2.InsertRequest.SerializeToString,
                response_deserializer=attentiondb__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/attentiondb.AttentionDB/Delete',
                request_serializer=attentiondb__pb2.DeleteRequest.SerializeToString,
                response_deserializer=attentiondb__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/attentiondb.AttentionDB/HealthCheck',
                request_serializer=attentiondb__pb2.HealthRequest.SerializeToString,
                response_deserializer=attentiondb__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.CreateCollection = channel.unary_unary(
                '/attentiondb.AttentionDB/CreateCollection',
                request_serializer=attentiondb__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=attentiondb__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.GetCollectionSettings = channel.unary_unary(
                '/attentiondb.AttentionDB/GetCollectionSettings',
                request_serializer=attentiondb__pb2.GetCollectionSettingsRequest.SerializeToString,
                response_deserializer=attentiondb__pb2.GetCollectionSettingsResponse.FromString,
                _registered_method=True)
        self.AlterCollection = channel.unary_unary(
                '/attentiondb.AttentionDB/AlterCollection',
                request_serializer=attentiondb__pb2.AlterCollectionRequest.SerializeToString,
                response_deserializer=attentiondb__pb2.AlterCollectionResponse.FromString,
                _registered_method=True)


class AttentionDBServicer:
    """Missing associated documentation comment in .proto file."""

    def Attend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlterCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttentionDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Attend': grpc.unary_unary_rpc_method_handler(
                    servicer.Attend,
                    request_deserializer=attentiondb__pb2.AttendRequest.FromString,
                    response_serializer=attentiondb__pb2.AttendResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=attentiondb__pb2.InsertRequest.FromString,
                    response_serializer=attentiondb__pb2.InsertResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=attentiondb__pb2.DeleteRequest.FromString,
                    response_serializer=attentiondb__pb2.DeleteResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=attentiondb__pb2.HealthRequest.FromString,
                    response_serializer=attentiondb__pb2.HealthResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=attentiondb__pb2.CreateCollectionRequest.FromString,
                    response_serializer=attentiondb__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'GetCollectionSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionSettings,
                    request_deserializer=attentiondb__pb2.GetCollectionSettingsRequest.FromString,
                    response_serializer=attentiondb__pb2.GetCollectionSettingsResponse.SerializeToString,
            ),
            'AlterCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterCollection,
                    request_deserializer=attentiondb__pb2.AlterCollectionRequest.FromString,
                    response_serializer=attentiondb__pb2.AlterCollectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'attentiondb.AttentionDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('attentiondb.AttentionDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttentionDB:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Attend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/attentiondb.AttentionDB/Attend',
            attentiondb__pb2.AttendRequest.SerializeToString,
            attentiondb__pb2.AttendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/attentiondb.AttentionDB/Insert',
            attentiondb__pb2.InsertRequest.SerializeToString,
            attentiondb__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/attentiondb.AttentionDB/Delete',
            attentiondb__pb2.DeleteRequest.SerializeToString,
            attentiondb__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/attentiondb.AttentionDB/HealthCheck',
            attentiondb__pb2.HealthRequest.SerializeToString,
            attentiondb__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/attentiondb.AttentionDB/CreateCollection',
            attentiondb__pb2.CreateCollectionRequest.SerializeToString,
            attentiondb__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/attentiondb.AttentionDB/GetCollectionSettings',
            attentiondb__pb2.GetCollectionSettingsRequest.SerializeToString,
            attentiondb__pb2.GetCollectionSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AlterCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/attentiondb.AttentionDB/AlterCollection',
            attentiondb__pb2.AlterCollectionRequest.SerializeToString,
            attentiondb__pb2.AlterCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
